### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by tony-engineering** [Humanitec/build-push-to-humanitec#2]
When you run into an error concerning repository credentials, the Github UI is showing a message 
`Did you add the token to your Github Secrets? http:/docs.humanitec.com/connecting-your-ci#github-actions`
The documentation link http:/docs.humanitec.com/connecting-your-ci#github-actions is broken.

**Comment by Nilsty** [comment]
Thanks for highlighting this issue, @tony-engineering 
We have fixed it now.
